name: Backend CI

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    # If your runner has extra labels, add them (case-sensitive), e.g.:
    # runs-on: [self-hosted, linux, x64]
    runs-on: self-hosted

    strategy:
      matrix: { node-version: [22] }

    # Expose secrets as env vars for all steps
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: ${{ secrets.PORT }}
      PROD_ENV: ${{ secrets.PROD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      # ---- PM2 present + tolerant cleanup ----
      - name: Ensure PM2 is installed
        run: npm i -g pm2

      - name: Stop previous app if running
        run: |
          pm2 delete lostandfound-backend || true
          pm2 kill || true

      # ---- Backend ----
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

      # ---- Frontend ----
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      # ---- Write .env only if provided (no 'if:' expression needed) ----
      - name: Write Backend .env (if provided)
        working-directory: ./backend
        run: |
          if [ -n "$PROD_ENV" ]; then
            printf "%s" "$PROD_ENV" > .env
            echo ".env written"
          else
            echo "PROD_ENV not set; skipping .env write"
          fi

      # ---- Start backend with a named PM2 process ----
      - name: Start backend with PM2
        working-directory: ./backend
        run: |
          pm2 start npm --name lostandfound-backend -- run start
          pm2 save

      - name: PM2 status
        run: pm2 status
