name: Backend CI

on:
  push:
    branches:
      - main  # Trigger CI on pushes to the main branch

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22] # Test on multiple Node.js versions

    # If you stored secrets in a GitHub Environment, set its name here:
    # environment:
    #   name: production  # <-- change to your environment name

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Ensure PM2 is installed
        run: npm i -g pm2

      - name: Stop PM2 app if running (no-op OK)
        run: pm2 stop lostandfound-backend || echo "App not running"

      # Install dependencies for backend
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          npm install --global yarn
          yarn --version
          yarn install

      # Install dependencies for frontend
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          df -h
          rm -rf ./build
          yarn install
          yarn run build

      # Run backend tests
      - name: Run Backend Tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        working-directory: ./backend
        run: npm test

      # (Optional) Root npm ci is usually unnecessary; remove if you don't need it
      # - run: npm ci

      - name: Write .env for backend (from PROD secret)
        working-directory: ./backend
        run: |
          touch .env
          printf "%s" "${{ secrets.PROD }}" > .env

      # Use your working PM2 command with a restart fallback
      - name: Start backend with PM2 (npm start)
        working-directory: ./backend
        run: |
          pm2 start npm --name lostandfound-backend -- start || pm2 restart lostandfound-backend

      - name: Save PM2 process list
        run: pm2 save || true
